// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoXd8wMdKm_ORaOaigclIXaStJ3JTkdyI',
    appId: '1:737040695515:web:b4de4840c5aa11bcb7ccfe',
    messagingSenderId: '737040695515',
    projectId: 'gazathon-dbd3d',
    authDomain: 'gazathon-dbd3d.firebaseapp.com',
    storageBucket: 'gazathon-dbd3d.appspot.com',
    measurementId: 'G-26J3L5TJL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_FSS1gwp2LXo9BvlB9Gto1xBvEF6Fk8',
    appId: '1:737040695515:android:f7d6d62315f2bf28b7ccfe',
    messagingSenderId: '737040695515',
    projectId: 'gazathon-dbd3d',
    storageBucket: 'gazathon-dbd3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANGUOlDAaqFzk-MQOBcMw6Igki6LomOQs',
    appId: '1:737040695515:ios:f260126e0440a1d9b7ccfe',
    messagingSenderId: '737040695515',
    projectId: 'gazathon-dbd3d',
    storageBucket: 'gazathon-dbd3d.appspot.com',
    iosBundleId: 'com.example.nasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANGUOlDAaqFzk-MQOBcMw6Igki6LomOQs',
    appId: '1:737040695515:ios:f260126e0440a1d9b7ccfe',
    messagingSenderId: '737040695515',
    projectId: 'gazathon-dbd3d',
    storageBucket: 'gazathon-dbd3d.appspot.com',
    iosBundleId: 'com.example.nasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoXd8wMdKm_ORaOaigclIXaStJ3JTkdyI',
    appId: '1:737040695515:web:8a2a40a621705289b7ccfe',
    messagingSenderId: '737040695515',
    projectId: 'gazathon-dbd3d',
    authDomain: 'gazathon-dbd3d.firebaseapp.com',
    storageBucket: 'gazathon-dbd3d.appspot.com',
    measurementId: 'G-VCHW67SYMH',
  );
}
